### ISSUE TITLE
Should PerformanceObserver.observe(... buffered=true}) work for LongTasks?

### ISSUE THREAD

**Issue by npm1** [w3c/longtasks#41]
In the observe() description[1], when the buffered flag is set, the performance buffer entries are added to the observer buffer. There are no longtask entries in the performance buffer, but I think that it could be useful to expose previous longtask entries when the buffered flag is on. Any thoughts on this? This would require some spec change here and/or in Performance Timeline.

[1] https://w3c.github.io/performance-timeline/#observe-method

**Comment by tdresser** [comment]
We should support the |buffered| flag for long tasks - you're right that this will require a spec change.

**Comment by npm1** [comment]
If we unify buffer processing model, we'll need to know how this will fit with long tasks which are currently not exposed to the performance timeline.

**Comment by philipwalton** [comment]
Lack of buffering was a big problem for us in the TTI polyfill (since it required an additional step where users added some code to the head of their pages).

This is less of a problem as we're moving away from TTI for RUM, but I still think we want buffering for long tasks in general, as there's no other way to get them without it.

**Comment by igrigorik** [comment]
Agreed. 

Per our intent and design for PerfObserver, we said that all entry types should be buffered up to onload. There is no reason to exclude long tasks, right?

**Comment by npm1** [comment]
cc @yoavweiss. In the last call we discussed the objective to unify the processing model of buffers of entry types (unclear to me what would happen to long tasks - would they get a buffer?). Someone also mentioned that we should not buffer just until onload because feedback from last TPAC was that this was not sufficient. The idea of buffering until reaching some buffer max size floated around.

I think the buffered flag is pretty urgent and should not be punted on any intent to unify the processing model. If anything, the buffered flag is the one thing that the entryType buffers will have in common. Adding this flag will not make unifying the models any harder. And I think unifying the processing models will not make the need for a buffered flag disappear.

**Comment by igrigorik** [comment]
@npm1 agreed. 

> Someone also mentioned that we should not buffer just until onload because feedback from last TPAC was that this was not sufficient.

I believe this was the comment about "if I want to load the script after onload, because I don't want to block onload, etc..". I'm sympathetic to that, but I don't think picking an arbitrary number of entries to buffer offers any better solution — I'm sure we'll find sites that load a ton of resources prior to onload and exhaust the buffer before someone registers their script. `onload`, despite all its warts, is a well specced and understood concept, and I still think we should anchor on that.

**Comment by tdresser** [comment]
Also see #26, regarding whether we should support the PerformanceTimeline API.

@nicjansma may have thoughts here.

**Comment by nicjansma** [comment]
From my perspective, any sort of buffering is better than nothing.  I think we've talked about several options in the past:

1. Buffering entries until they hit a per-spec limit N
2. Buffering all entries that happen before `onload` (and not clearing the buffer at that point)
3. Buffering all entries that happen before `onload` (and clearing the buffer at that point)

Taking Boomerang RUM through mPulse as an example, in the wild Boomerang is only on the page about 40% of the time before `onload`. This is due to intentionally loading async and with lower priority, being loaded by tag managers, not blocking `onload`, etc.  So anything that we can use to look-back in time to gather data is helpful for the majority of our cases.

As a result, (3) above, when entries are dropped at `onload`, isn't ideal.

(As Philip mentions, the alternate is to add additional code to the head on every page that turns on monitoring, buffers, and hands-off to RUM.  We'd prefer to not do this if possible to avoid bloat).

So ideally, we'd love to get by-default buffering that sticks around, whether it's by a per-spec limit N (1) or the `onload` event (2).  Both have some downsides, but, some data is better than nothing, and for cases where the default is not enough, sites could add code to their head if needed.

I do think we can find reasonable per-spec limits N (1) for the majority of the Perf-Observable specs.  Even if the buffer limits are hit in complex pages, RUM can still use whatever data was gathered.

As a side note, IIRC there was a concern with LongTasks that turning it on by default for every page load might have undesired overhead.  Is that still a concern?

**Comment by npm1** [comment]
FWIW we're going with the per-spec limits. In fact we already have this to specify buffered flag support https://w3c.github.io/timing-entrytypes-registry/#registry :)

Regarding longtasks, the only blocker right now is proving that there would not be a performance impact when instrumenting long tasks by default (at least until the 'long tasks buffer' becomes full).

**Comment by philipwalton** [comment]
If we're dropping entries because the buffer is full, do we have a way for a site to detect that? This seems critical in ensuring data is reported reliably.

**Comment by npm1** [comment]
We want to avoid exposing a full buffer processing logic like the one done for ResourceTiming. So currently there is no precise way to know. If your first callback from P.O. with buffered flag contains >= maxBufferSize entries, that's a strong signal that the buffer is full.

**Comment by philipwalton** [comment]
> We want to avoid exposing a full buffer processing logic like the one done for ResourceTiming.

I'm actually not familiar with what we expose (buffer-wise) for RT, but is the reason related to security concerns? I wasn't thinking we needed to expose anything other than the fact that entries may have been dropped.

> o currently there is no precise way to know. If your first callback from P.O. with buffered flag contains >= maxBufferSize entries, that's a strong signal that the buffer is full.

This seems fine as long as `maxBufferSize` is exposed. It may be sufficient to infer it from the spec, but if the spec'ed amount ever changes (or if browsers implement it differently) then it may not be a useful signal.

**Comment by npm1** [comment]
> I'm actually not familiar with what we expose (buffer-wise) for RT, but is the reason related to security concerns? I wasn't thinking we needed to expose anything other than the fact that entries may have been dropped.

Not security reasons. We could expose some way for PerformanceObserver to know that the buffer has become full.

> This seems fine as long as `maxBufferSize` is exposed. It may be sufficient to infer it from the spec, but if the spec'ed amount ever changes (or if browsers implement it differently) then it may not be a useful signal.

Right, currently it is meant to be hard-coded in the registry but it's true that we may want an easier way for developers to tell that their buffered flag P.O. is too late (i.e. missed entries).

**Comment by toddreifsteck** [comment]
This is similar to #26 

We've kept in in L1 for now. Lets discuss on next triage call.

**Comment by npm1** [comment]
This is now done, as the longtasks maxBufferSize is now set to 200 and buffering should work for those.
