### ISSUE TITLE
Combination of paint timing and long tasks can expose precise paint timing

### ISSUE THREAD

**Issue by rniwa** [w3c/longtasks#80]
[Update the rendering](https://html.spec.whatwg.org/multipage/webappapis.html#update-the-rendering) makes paint timing for each document right before updating the rendering (painting) in step 13 and computes *rendering end time* for reporting long tasks in step 12. Because this sandwitches the painting operation, it can be used to measure the paint time with a high precision.

**Comment by npm1** [comment]
Talked about this on the call. We're gonna remove longtasks from Update the rendering because 1. not implemented 2. it should be tackled by a separate Frame Throughput API instead which cares more about how often frames are updated instead of surfacing 'long frames'. Removing that will fix this issue.

**Comment by npm1** [comment]
Fixed by https://github.com/whatwg/html/pull/5459

**Comment by noamr** [comment]
Just ran into this... The Chrome implementation does report longtasks for "update the rendering" as it's done in a separate `BeginFrame` task. Also `requestAnimationFrame` callback etc. are inside the "update the rendering" step so removing this means we don't report long tasks generated inside rAF callbacks. Not sure how to go about this.
